### ISSUE TITLE
Track_infos keyerror

### ISSUE THREAD

**Issue by dag7dev** [DavidBuchanan314/beatstar-tools#2]
Running anything gives:
```
Traceback (most recent call last):
  File "/home/me/beatstar-tools/get_rewards.py", line 42, in <module>
    config = GameConfig(session)
  File "/home/me/beatstar-tools/gameconfig.py", line 21, in __init__
    self.tracks = {track['id']: track for track in self.config["track_infos"]}
KeyError: 'track_infos'
```
No clues how to solve this issue.

**Comment by DavidBuchanan314** [comment]
Looks like they've changed how they store the game data. You can work around this for now by just commenting out everything that's broken.

I don't really play the game anymore so I'm unlikely to investigate further, but I'll accept any PR that fixes this.

**Comment by dag7dev** [comment]
FYI: I've commented everything that gave me error and obviously nothing is working anymore. I'd suggest to put a disclaimer in the README remarking that you'll no longer work on this, unless you're considering to archive this repo.

It's a pity, I used to love this small tool! :(

**Comment by ExternalAddress4401** [comment]
I don't do python but the point is they've removed the song info from the GameConfig and have instead put it into a SongConfig with the following proto

```
songconfig_proto = {
	1: ("version", String()),
	3: ("GameSKUs", Packed({
		1: ("id", Varint()),
		2: ("idLabel", String())
	})),
	4: ("Beatmaps", {
		1: ("id", Varint()),
		5: ("availability", Varint()),
		21: ("Song_id", Varint()),
		37: ("idLabel", String()),
		46: ("BeatmapVariantReference_id", Varint()),
	}),
	5: ("BeatmapVariants", {
		1: ("id", Varint()),
		2: ("idLabel", String()),
		3: ("Song_id", Varint()),
		4: ("MaxNumLanes", Varint()),
		5: ("MaxScore", Varint()),
		6: ("Difficulty_id", Varint()),
		9: ("IsComplete", Varint()),
		10: ("InteractionsReference_id", Varint()),
		12: ("NumStars", Varint()),
		13: ("InteractionsAsset_id", String()),
		15: ("Description", String()),
	}),
	7: ("SongDifficulties", Packed({
		1: ("id", Varint()),
		3: ("difficulty", Varint()),
		15: ("idLabel", String())
	})),
	8: ("SongTags", Packed({
		1: ("id", Varint()),
		14: ("idLabel", String()),
		21: ("sku_id", Varint())
	})),
	10: ("SongWeightingTags", Packed({
		1: ("id", Varint()),
		2: ("idLabel", String())
	})),
	11: ("BanGroups", Packed({
		1: ("id", String()),
		4: ("blankedBanned", Varint())
	})),
	12: ("SongGroups", Packed({
		1: ("id", Varint()),
		2: ("idLabel", String())
	})),
	13: ("SongMetas", Packed({
		1: ("id", Varint()),
		2: ("idLabel", String())
	}))
}
```

**Comment by thriller140** [comment]
I'm would love a fix to be implemented, but I am not sure on how to do that given this new SongConfig they have added.

For me, the workaround for commenting the parts that are broken is working.

**Comment by ExternalAddress4401** [comment]
login.py has a list of CMS files you can request: https://github.com/DavidBuchanan314/beatstar-tools/blob/main/login.py#L121

Add a SongConfig to that to grab that once it's run.

In the case of list_all_songs

https://github.com/DavidBuchanan314/beatstar-tools/blob/main/gameconfig.py#L1

You no longer want GameConfig you'd want SongConfig which you'd have to make and parse with the new proto like with gameconfig.py: https://github.com/DavidBuchanan314/beatstar-tools/blob/main/login.py#L121

You'd then have to modify the data relationships using the SongConfig instead.
